#Test Senaryosu: Eğitimler Eğitim Kanalı,Eğitim Dili,Eğitim Seviyesi Sınıflandırma Kontrolü
#Test Case1: Eğitim Kanalı Kontrolü
#Eğitim kanalı kontrol casei
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from myconstants import categoryConstants as cco
from time import sleep

class TestEducationchannelcontrol():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.get(cco.PORTAL_URL)
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_educationchannelcontrol(self):
    # self.driver.get("https://www.btkakademi.gov.tr/portal")
    # self.driver.set_window_size(1382, 744)
    educations_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.EDUCATIONS_BUTTON_XPATH)))
    educations_button.click()
    allcategories_button=WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.XPATH,cco.ALL_CATEGORIES_BUTTON_XPATH)))
    allcategories_button.click()
    openclosecategory_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.CATEGORIES_OPEN_CLOSE_BUTTON_XPATH)))
    openclosecategory_button.click()
    education_channel_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.EDUCATION_CHANNEL_BUTTON_XPATH)))
    education_channel_button.click()
    inclass_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.INCLASS_BUTTON_XPATH)))
    inclass_button.click()
    educationchannelresult=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.EDUCATION_CHANNEL_RESULT_XPATH)))
    assert educationchannelresult.text=="Arama kriterlerine uygun sonuç bulunamadı."
    clean_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.CLEAN_BUTTON_XPATH)))
    clean_button.click()
    elearn_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.ELEARN_BUTTON_XPATH)))
    elearn_button.click()
    evidence_elearn_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.EVIDENCE_ELEARN_XPATH)))
    assert evidence_elearn_button.text=="30 Eğitim Bulundu"
    
    # self.driver.find_element(By.CSS_SELECTOR, "#gbt_main-header-catalog > #gbt_main-header-catalog-icon > #gbt_main-header-catalog-icon").click()
    # self.driver.find_element(By.XPATH, "//span/a").click()
    # self.driver.find_element(By.CSS_SELECTOR, "#gbt_catalog-main-left-menu-1 svg").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".ant-collapse-item:nth-child(2) svg").click()
    # self.driver.find_element(By.XPATH, "//li[2]/span/label/span[2]").click()
    # WebDriverWait(self.driver, 3).until(ec.visibility_of_element_located((By.XPATH, "//*[@id=\"gbt_catalog-main-right-filterbox-main-count\"]")))
    # assert self.driver.find_element(By.XPATH, "//p[@id=\'gbt_catalog-main-right-filterbox-main-count\']").text == "30 Eğitim Bulundu"
    # self.driver.find_element(By.ID, "gbt_catalog-main-left-menu-2-clear").click()
    # self.driver.find_element(By.XPATH, "//*[@id=\"undefined-list\"]/li[1]/span/label/span[2]").click()
    # WebDriverWait(self.driver, 3).until(ec.visibility_of_element_located((By.XPATH, "//*[@id=\"gbt_catalog-main-right-filterbox-main-count\"]")))
    # assert self.driver.find_element(By.XPATH, "//*[@id=\"gbt_catalog-main-right-filterbox-main-count\"]").text == "0 Eğitim Bulundu"
  
