#Test Senaryosu: Eğitimler Eğitim Kanalı,Eğitim Dili,Eğitim Seviyesi Sınıflandırma Kontrolü
#Test Case2: Eğitim Dili Filtreleme Kontrolü
#Eğitim dili filtresi kontrolü casei
#test başarılı
#assert kısmına tekrar bakmak lazım çünkü listeyi yani çıkan eğitimleri assert yapmak gerekiyor.
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from myconstants import categoryConstants as cco
from time import sleep

class TestLanguageeducationcontrol():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.get(cco.PORTAL_URL)
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_languageeducationcontrol(self):
    # self.driver.get("https://www.btkakademi.gov.tr/portal")
    # self.driver.set_window_size(1382, 744)
    educations_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.EDUCATIONS_BUTTON_XPATH)))
    educations_button.click()
    allcategories_button=WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.XPATH,cco.ALL_CATEGORIES_BUTTON_XPATH)))
    allcategories_button.click()
    openclosecategory_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.CATEGORIES_OPEN_CLOSE_BUTTON_XPATH)))
    openclosecategory_button.click()
    education_language_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.EDUCATIONLANGUAGE_OPEN_CLOSEBUTTON_XPATH)))
    education_language_button.click()
    turkish_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.TURKISH_BUTTON_XPATH)))
    turkish_button.click()
    listOfCourses= self.driver.find_elements(By.XPATH,"//*[@id='gbt_catalog-main-right-course']")
    testResult= len(listOfCourses)==12
   


#     listOfCourses = driver.find_elements(By.CLASS_NAME,"course-listing") #find elements kullandık.
# testResult = len(listOfCourses) == 8

    # element = self.driver.find_element(By.CSS_SELECTOR, "#gbt_index-banner-category-0 > #gbt_index-banner-category-0")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    # element = self.driver.find_element(By.CSS_SELECTOR, "body")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element, 0, 0).perform()
    # self.driver.find_element(By.CSS_SELECTOR, "#gbt_main-header-catalog > #gbt_main-header-catalog-icon > #gbt_main-header-catalog-icon").click()
    # WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.LINK_TEXT, "Tüm Kategoriler")))
    # self.driver.find_element(By.CSS_SELECTOR, "#gbt_main-header-catalog > #gbt_main-header-catalog-icon > #gbt_main-header-catalog-icon").click()
    # self.driver.find_element(By.LINK_TEXT, "Tüm Kategoriler").click()
    # self.driver.find_element(By.CSS_SELECTOR, "#gbt_catalog-main-left-menu-1 svg").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".ant-collapse-item:nth-child(3) svg").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".ant-menu-item-active .ant-checkbox-inner").click()
    # self.driver.find_element(By.ID, "gbt_catalog-main-left-menu-3-clear").click()
  
