#Test Senaryosu: Eğitimler Eğitim Kanalı,Eğitim Dili,Eğitim Seviyesi Sınıflandırma Kontrolü
#Test Case3: Eğitim Seviyesi Filtreleme Kontrolü
# #Eğitim seviyesi filtreleme casei
#test geçti başarılı.
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from myconstants import categoryConstants as cco
from time import sleep

class TestLeveleducationcontrol():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.get(cco.PORTAL_URL)
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_leveleducationcontrol(self):
    # self.driver.get("https://www.btkakademi.gov.tr/portal")
    # self.driver.set_window_size(1382, 744)
    educations_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.EDUCATIONS_BUTTON_XPATH)))
    educations_button.click()
    allcategories_button=WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.XPATH,cco.ALL_CATEGORIES_BUTTON_XPATH)))
    allcategories_button.click()
    openclosecategory_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.CATEGORIES_OPEN_CLOSE_BUTTON_XPATH)))
    openclosecategory_button.click()
    education_level_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.EDUCATION_LEVEL_BUTTON_XPATH)))
    education_level_button.click()
    beginning_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.BEGINNING_BUTTON_XPATH)))
    beginning_button.click()
    sleep(5)
    beginning_evidence=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.BEGINNING_EVIDENCE_XPATH)))
    assert beginning_evidence.text=="198 Eğitim Bulundu"
    beginning_education_evidence=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.BEGINNING_EDUCATION_XPATH)))
    assert beginning_education_evidence.text=="Temel Seviye"
    # self.driver.find_element(By.CSS_SELECTOR, "#gbt_main-header-catalog > #gbt_main-header-catalog-icon > #gbt_main-header-catalog-icon").click()
    # WebDriverWait(self.driver, 3).until(expected_conditions.visibility_of_element_located((By.XPATH, "//span/a")))
    # self.driver.find_element(By.CSS_SELECTOR, "#gbt_main-header-catalog > #gbt_main-header-catalog-icon > #gbt_main-header-catalog-icon").click()
    # self.driver.find_element(By.LINK_TEXT, "Tüm Kategoriler").click()
    # self.driver.find_element(By.CSS_SELECTOR, "#gbt_catalog-main-left-menu-1 path").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".ant-collapse-item:nth-child(4) svg").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".ant-menu-item-active .ant-checkbox-inner").click()
    # WebDriverWait(self.driver, 3).until(expected_conditions.visibility_of_element_located((By.ID, "gbt_catalog-main-right-filterbox-main-count")))
    # assert self.driver.find_element(By.ID, "gbt_catalog-main-right-filterbox-main-count").text == "198 Eğitim Bulundu"
    # WebDriverWait(self.driver, 3).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "div:nth-child(1) > .ant-ribbon-wrapper .txt-secondary")))
    # assert self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .ant-ribbon-wrapper .txt-secondary").text == "Temel Seviye"
  
