#Test Senaryosu: Arama Textboxı Kullanılarak Eğitim Araması Kontrolü
#Test Case1: Arama Yapılarak Kursların Listelenmesi Kontrolü
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from myconstants import categoryConstants as cco
from time import sleep


class TestSearchingtextbox():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.get(cco.PORTAL_URL)
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchingtextbox(self):
    # self.driver.get("https://www.btkakademi.gov.tr/portal")
    # self.driver.set_window_size(1382, 744)
    searching_textbox=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.NAME,cco.SEARCHING_TEXTBOX_NAME)))
    searching_textbox.click()
    searching_textbox.send_keys("Yazılım Testi")
    searching_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.SEARCHING_BUTTON_XPATH)))
    searching_button.click()
    searching_result=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.SEARCHING_RESULT_XPATH)))
    assert searching_result.text =='Arama Sonuçları: "Yazılım Testi"'  
    testing_education_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.TESTING_EDUCATION_XPATH)))
    assert testing_education_button.text=="Yazılım Testine Giriş"
    
    # elements = self.driver.find_elements(By.XPATH, "//*[@id=\'gbt_app-body-container\']/div/div[2]/div/div[2]/div")
    # assert len(elements) > 0
  
