#Test Senaryosu: Arama Textboxı Kullanılarak Eğitim Araması Yapılması
#Test Case2: Uygunsuz (Başarısız) Arama Yapılarak Kursların Listelenmesi Kontrolü
#test fail oldu.
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from time import sleep
from myconstants import categoryConstants as cco


class TestFailedsearchingtextbox():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.get(cco.PORTAL_URL)
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_failedsearchingtextbox(self):
    # self.driver.get("https://www.btkakademi.gov.tr/portal")
    # self.driver.set_window_size(1382, 744)
    # sleep(5)
    #self.driver.find_element(By.NAME, "q").click()
    searchingtextbox=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.NAME,cco.SEARCHING_TEXTBOX_NAME)))
    #usernameInput = WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.ID,"user-name")))
    searchingtextbox.click()
    searchingtextbox.send_keys("123")
    searchingbutton=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.SEARCHING_BUTTON_XPATH)))
    searchingbutton.click()
    
    searchingresult=WebDriverWait(self.driver,10).until(ec.visibility_of_element_located((By.XPATH,cco.SEARCHING_RESULT_XPATH)))
    assert searchingresult.text == "“Belirtilen kriterlere uygun eğitim bulunamamıştır.”"
  
