#Test Senaryosu  Adı: Seçilen Kategoriye göre Kursların Listelenmesi
#Test Case1: Kategori seçilerek kursların listelenmesi kontrolü
#kategori seçimi
# Generated by Selenium IDE
#başarılı geçti test
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from myconstants import categoryConstants as cco

from time import sleep

class TestChoicecategory():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.get(cco.PORTAL_URL)
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_choicecategory(self):
    #self.driver.get("https://www.btkakademi.gov.tr/portal")
    #self.driver.set_window_size(1382, 744)
    sleep(5)
    softwareworldbutton=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.SOFTWARE_WORLD_BUTTON_XPATH)))
    softwareworldbutton.click()
    pythoneducation=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.REVEALED_EDUCATION_XPATH)))
    assert pythoneducation.text ==cco.EVIDENCE_EDUCATION_TEXT
  
