#Test Senaryosu  Adı: Seçilen Kategoriye göre Kursların Listelenmesi
#Test Case1: Kategori seçilerek kursların listelenmesi kontrolü-2
#kategori seçme 2
#test başarılı geçti.
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from myconstants import categoryConstants as cco

class TestCategory():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.get(cco.PORTAL_URL)
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_category(self):
    # self.driver.get("https://www.btkakademi.gov.tr/portal")
    # self.driver.set_window_size(1382, 744)
    system_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.ID,cco.SYSTEM_WORLD_BUTTON_ID)))
    system_button.click()
    system_engineer_education=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.SYSTEM_ENGINEER_EDUCATION_XPATH)))
    assert system_engineer_education.text == "Sistem Mühendisliği"
  
