#Test Senaryosu  Adı: Seçilen Kategoriye göre Kursların Listelenmesi
#Test Case4: İki Farklı Kategori Seçimi Kontrolü
#2 kategori seçimi
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from myconstants import categoryConstants as cco

class TestChoice2category():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_choice2category(self):
    # self.driver.get("https://www.btkakademi.gov.tr/portal")
    # self.driver.set_window_size(1382, 744)
    system_button=self.driver.find_element(By.ID,cco.SYSTEM_WORLD_BUTTON_ID)
    system_button.click()
    self.driver.find_element(By.XPATH, "//li[2]/div/span/label/span/span").click()
    WebDriverWait(self.driver, 0.5).until(ec.visibility_of_element_located((By.XPATH, "//label/span")))
    WebDriverWait(self.driver, 0.5).until(ec.visibility_of_element_located((By.XPATH, "//label/span")))
    assert self.driver.find_element(By.ID, "gbt_catalog-main-right-filterbox-main-title").text == "Eğitimler"
    WebDriverWait(self.driver, 0.5).until(ec.visibility_of_element_located((By.XPATH, "//*[@id=\"gbt_catalog-main-right-course\"]/div[1]/div/div[1]/a/div/div/div")))
    assert self.driver.find_element(By.XPATH, "//*[@id=\"gbt_catalog-main-right-course\"]/div[1]/div/div[1]/a/div/div/div").text == "Python ile Makine Öğrenmesi Uygulamaları"
    WebDriverWait(self.driver, 0.5).until(ec.visibility_of_element_located((By.XPATH, "//*[@id=\"gbt_catalog-main-right-course\"]/div[2]/div/div[1]/a/div/div/div")))
    assert self.driver.find_element(By.XPATH, "//*[@id=\"gbt_catalog-main-right-course\"]/div[2]/div/div[1]/a/div/div/div").text == "SIEM Temelleri"
  
