#Test Senaryosu  Adı: Seçilen Kategoriye göre Kursların Listelenmesi
#Test Case3: Tüm Eğitimler Sıralama Kontrolü
#eğitimleri en beğenilenlere göre sıralama kontrolü
# Generated by Selenium IDE
#test başarılı geçti.
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from myconstants import categoryConstants as cco
from time import sleep

class TestArrangementcategory():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.get(cco.PORTAL_URL)
    self.driver.maximize_window()
    self.vars = {}
  
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_arrangementcategory(self):
    #self.driver.get("https://www.btkakademi.gov.tr/portal")
    #self.driver.set_window_size(1382, 744)
    education_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.EDUCATIONS_BUTTON_XPATH)))
    education_button.click()
    
    allcategories_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.ALL_CATEGORIES_BUTTON_XPATH)))
    allcategories_button.click()
    
    choice_arrangement_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.CHOICE_ARRANGEMENT_BUTTON_XPATH)))
    choice_arrangement_button.click()
    favorites_button=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.FAVORITES_BUTTON_XPATH)))
    favorites_button.click()
    educationcount=WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((By.XPATH,cco.EDUCATION_COUNT_XPATH)))
    assert educationcount.text ==cco.EVIDENCE3_EDUCATION_TEXT
